### ISSUE TITLE
qmanager: preserve reservations across scheduler loops (and optimize reservation clearing)

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#508] opened 2019-08-09 18:50 UTC
Right now (in #504), at the end of every scheduler loop, reservations are cleared.

One minor change would be to clear reservations at the start of each scheduler loop.  This would mean that reservation information is available for querying in between scheduler loops (e.g., to estimate when a job will start)

As an optimization in backfill schedulers, we should only clear reservations when necessary.  As a first cut, we can keep reservations across scheduler loops and only clear them when a job completes or when a new job is submitted whose priority is higher than a job with an existing reservation.  As a second cut, we can reduce the number of reservations cleared in that latter case by only clearing reservations of jobs whose priority is lower than the new job.

**Comment by dongahn** [comment] 2020-08-20 07:05
I am looking at this and I have to believe making the following one-line change can give this functionality. 

```diff
diff --git a/qmanager/policies/queue_policy_bf_base_impl.hpp b/qmanager/policies/queue_policy_bf_base_impl.hpp
index da3fadab..027e7432 100644
--- a/qmanager/policies/queue_policy_bf_base_impl.hpp
+++ b/qmanager/policies/queue_policy_bf_base_impl.hpp
@@ -185,8 +185,8 @@ int queue_policy_bf_base_t<reapi_type>::run_sched_loop (void *h,
 {
     int rc = 0;
     rc = cancel_completed_jobs (h);
-    rc += allocate_orelse_reserve_jobs (h, use_alloced_queue);
     rc += cancel_reserved_jobs (h);
+    rc += allocate_orelse_reserve_jobs (h, use_alloced_queue);
     return rc;
 }
```

This seems to mostly work. But once time on my Mac OS/X docker, I got the following error message. This is as if the reservation cancel request from `qmanager` arrive after the match request on the same jobid. 

This shouldn't be the case because of the RPC non-overtaking rule (a later RPC cannot overtake an earlier RPC). 


```console
ahn1@81451f60e736:/usr/src$ flux start -s 4

ahn1@81451f60e736:/usr/src$ flux mini submit -N 2 -n 8 sleep 360

ahn1@81451f60e736:/usr/src$ flux mini submit -N 2 -n 8 sleep 360
699173699584
ahn1@81451f60e736:/usr/src$ flux mini submit -N 2 -n 8 sleep 360
711672725504
ahn1@81451f60e736:/usr/src$ flux resource list
     STATE NNODES   NCORES    NGPUS
      free      0        0        0
 allocated      4       16        0
      down      0        0        0

 ahn1@81451f60e736:/usr/src$ flux jobs
  JOBID USER     NAME       ST NTASKS NNODES  RUNTIME RANKS
    ƒKhH5jzF ahn1     sleep      PD      8      -        - -
    ƒKNEay3M ahn1     sleep       R      8      2   5.447s [2-3]
    ƒAVsL9EP ahn1     sleep       R      8      2   25.54s [0-1]

ahn1@81451f60e736:/usr/src$ flux mini submit -N 2 -n 8 sleep 360

2020-08-20T03:50:24.133488Z sched-fluxion-resource.err[0]: match_request_cb: existent job (711672725504).: Invalid argument

```

I don't have a reliable reproducer as yet though.

**Comment by dongahn** [comment] 2020-08-20 18:52
We talked about this problem at our regularly scheduled meeting. @garlick mentioned if this is indeed out of order request invocation, this is concerning. @SteVwonder mentioned that if there is any other place where "match" is coming, which I don't know of any. I will see if I can reproduce reliably if at all.

**Comment by dongahn** [comment] 2020-08-25 03:19
Preliminary support has been added to https://github.com/dongahn/flux-sched/tree/starttime-estimate

**Comment by dongahn** [comment] 2020-09-01 04:27
PR #735 has been merged.

**Closed by dongahn** 2020-09-01 04:27 UTC
Labels: enhancement
