### ISSUE TITLE
t1018-rv1-bootstrap2.t: failure in flux-shed CI test over in flux-core

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#799] opened 2021-01-08 18:57 UTC
For the flux-core PR (https://github.com/flux-framework/flux-core/pull/3458), the flux-sched CI test failed with:

```
2021-01-08T05:11:00.9564100Z FAIL: t1018-rv1-bootstrap2.t 5 - rv1-bootstrap: resource idempotency preserved
```

I'm assuming this is just an intermittent failure, but I wanted to log it in case it starts to pop up more.  The full build log: https://gist.github.com/SteVwonder/05920bc917aac17deaee1dc63bd18605

**Comment by dongahn** [comment] 2021-01-12 06:16
Probably not the cause of this error but I see:

> 2021-01-08T05:06:05.8826545Z ./src/test/checks_run.sh: line 180: test: too many arguments

There is a minor bug in `checks_run.sh`:

```diff
runner@fv-az128-15:~/work/flux-sched/flux-sched/src/test$ diff checks_run.sh checks_run.sh.new 
180c180
< if test "$POISON" = "t" -a test "$PROJECT" = "flux-core"; then
---
> if test "$POISON" = "t" -a "$PROJECT" = "flux-core"; then
```

**Comment by dongahn** [comment] 2021-01-13 01:25
I believe this will be solved once PR #800 is merged.

**Comment by chu11** [comment] 2021-01-20 18:43
appeared to hit this in the centos 7 builder in https://github.com/flux-framework/flux-sched/pull/803

```
   rv1-bootstrap: creating a nested batch script
  
  expecting success: 
      JOBID=$(flux mini batch -n4 -N4 -c44 -g4 \
  	./nest.sh high 4 4 44 4 nest.json) &&
      $WAITFILE -t 600 -v -p \"R_lite\" nest.json &&
      jq " del(.execution.starttime, .execution.expiration) " \
  	nest.json > nest.norm.json &&
      flux job info ${JOBID} R | \
  	jq " del(.execution.starttime, .execution.expiration) " \
  	> job.norm.json &&
      test_cmp job.norm.json nest.norm.json
  
  waitfile: nest.json: 0.000s: No file yet
  waitfile: nest.json: 1.751s: wakeup
  waitfile: nest.json: 1.751s: File appeared with size 0
  waitfile: nest.json: 1.751s: back to sleep
  waitfile: nest.json: 600.001s: Timeout after 600s
  -rw-r--r-- 1 runner runner 0 Jan 20 18:12 nest.json
  not ok 4 - rv1-bootstrap: resource idempotency preserved
```

**Comment by dongahn** [comment] 2021-01-20 18:50
yeah this problem needs another look. For now, feel free to restart a runner.

**Closed** 2022-03-31 17:03 UTC
