### ISSUE TITLE
jobspec: accessing non-existant keys

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#439] opened 2018-08-24 17:29 UTC
As @trws pointed out, there are several areas where non-existant keys are accessed with the `[]` operator, which causes an exception.  One example is:
```C++
    if (!tasknode["command"]) {
        throw parse_error (tasknode, "Key \"command\" missing from task");
    }
```
In this scenario, if `command` doesn't exist, a `YAML::exception` will be raised before the `parse_error` can be thrown.  So each of those lines is dead code.

Per the `yaml-cpp` docs, we should use `FindValue` instead: https://github.com/jbeder/yaml-cpp/wiki/How-To-Parse-A-Document-(Old-API)#optional-keys

**Comment by grondo** [comment] 2019-02-05 17:19
Good point. I've transferred the issue to flux-sched.

**Comment by dongahn** [comment] 2020-08-28 22:50
Hmmm. I'm getting:

```
  CXX      libjobspec_conv_la-jobspec.lo
jobspec.cpp: In constructor ‘Flux::Jobspec::Task::Task(const YAML::Node&)’:
jobspec.cpp:226:19: error: ‘const class YAML::Node’ has no member named ‘FindValue’
     if (!tasknode.FindValue ("command")) {
                   ^~~~~~~~~
jobspec.cpp:237:19: error: ‘const class YAML::Node’ has no member named ‘FindValue’
     if (!tasknode.FindValue ("slot")) {
                   ^~~~~~~~~
jobspec.cpp:247:18: error: ‘const class YAML::Node’ has no member named ‘FindValue’
     if (tasknode.FindValue ("count")) {
                  ^~~~~~~~~
jobspec.cpp:260:18: error: ‘const class YAML::Node’ has no member named ‘FindValue’
     if (tasknode.FindValue ("distribution")) {
                  ^~~~~~~~~
jobspec.cpp:269:18: error: ‘const class YAML::Node’ has no member named ‘FindValue’
     if (tasknode.FindValue ("attributes")) {
```

**Comment by dongahn** [comment] 2020-08-28 23:33
I have to think that this is a non issue.

https://github.com/jbeder/yaml-cpp/wiki/How-To-Parse-A-Document-(Old-API)#optional-keys is with an old API.

For newer APIs that we use (API >= 0.5.0), https://github.com/jbeder/yaml-cpp/wiki/Tutorial explains:

> Querying for keys does not create them automatically (this makes handling optional map entries very easy)

My guess is, `operator[]` does not throw an exception any longer. Since I couldn't find the implement easily, I ran some tests instead. I found there are actually a whole bunch of jobspec tests under `/usr/src/t/data/resource/jobspecs/validation/` which include missing keys. They all pass; this suggests that the code is working as intended

For example,

```console
ahn1@403d49233119:/usr/src/t/data/resource/jobspecs/validation/invalid$ /usr/src/resource/libjobspec/flux-jobspec-validate task_missing_command.yaml
/usr/src/resource/libjobspec/flux-jobspec-validate: Key "command" missing from task
```

I will close this ticket. It you disagree, we can reopen.

**Closed** 2020-08-28 23:33 UTC
Labels: bug
