### ISSUE TITLE
Error to compile flux-sched

### ISSUE THREAD

**Issue by marceloamaral** [flux-framework/flux-sched#366] opened 2018-07-19 20:00 UTC
I am getting this error to compile the flux-sched

`/usr/include/c++/5/bits/stl_construct.h:75:7:` error: use of deleted function ‘boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>::stored_edge_property(const boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }`

does some one had similar issue? do you know how to fix that?

**Comment by tpatki** [comment] 2018-07-19 20:10
Hi Marcel, 
This might have to do with Boost library not supporting a certain C++ compiler. Seems to be a known issue in BGL. Which compilers/version are you using? Can you try a different g++ compiler, maybe?

- https://stackoverflow.com/questions/25395805/compile-error-with-boost-graph-1-56-0-and-g-4-6-4
- https://svn.boost.org/trac10/ticket/10382#no1

**Comment by tpatki** [comment] 2018-07-19 20:17
Hi Marcelo,
This might have to do with Boost library not supporting a certain C++ compiler or version. Seems to be a known issue in BGL. Which compiler/version are you using? Can you try a different one, maybe?

- https://stackoverflow.com/questions/25395805/compile-error-with-boost-graph-1-56-0-and-g-4-6-4
- https://svn.boost.org/trac10/ticket/10382#no1

**Comment by dongahn** [comment] 2018-07-19 20:50
I agree. This probably is due to a bug in the boost version you have.

Can you install boost 1.53 and compile flux-sched against it? Related issues and how to build sched with a side-installed boost are documented at https://github.com/flux-framework/flux-sched/issues/302

**Comment by marceloamaral** [comment] 2018-07-25 17:07
Hi, 

I tried ./configure --with-boost-libdir=my_local_compiled_boost_1_53_0_path

But I got the same error:
`/usr/include/c++/5/bits/stl_construct.h:75:7: error: use of deleted function 'boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>::stored_edge_property(const boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>&)'
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }`

Which boost version should I use?

**Comment by SteVwonder** [comment] 2018-07-25 17:47
@marceloamaral: it seems that newer versions of BGL have fixed this particular bug in their code.  In issue https://github.com/flux-framework/flux-sched/issues/297, @garlick was about to get 1.62 to work.  In an installation I have locally, 1.67 works.  Sorry I don't have an exact number.  We should probably track down the exact version that fixes it, but unfortunately the only boost bug report on the problem that I could find is still open :laughing: (https://svn.boost.org/trac10/ticket/10382)

FWIW, in a few days, I should have a working PR sent to spack so that you can just `spack install flux-sched@master` and have all the dependencies handled for you.

**Comment by dongahn** [comment] 2018-07-25 20:41
@marceloamaral and @SteVwonder : Hmmmm. This is odd. I was able to use 1.53 okay as it is the boost version installed on quartz:

```
quartz188{dahn}21: rpm -qa | grep boost
boost-math-1.53.0-27.el7.x86_64
boost-date-time-1.53.0-27.el7.x86_64
boost-filesystem-1.53.0-27.el7.x86_64
boost-python-1.53.0-27.el7.x86_64
boost-1.53.0-27.el7.x86_64
boost-signals-1.53.0-27.el7.x86_64
boost-regex-1.53.0-27.el7.x86_64
boost-atomic-1.53.0-27.el7.x86_64
boost-locale-1.53.0-27.el7.x86_64
boost-timer-1.53.0-27.el7.x86_64
boost-context-1.53.0-27.el7.x86_64
boost-chrono-1.53.0-27.el7.x86_64
boost-program-options-1.53.0-27.el7.x86_64
boost-test-1.53.0-27.el7.x86_64
boost-devel-1.53.0-27.el7.x86_64
boost-random-1.53.0-27.el7.x86_64
boost-graph-1.53.0-27.el7.x86_64
boost-system-1.53.0-27.el7.x86_64
boost-thread-1.53.0-27.el7.x86_64
boost-iostreams-1.53.0-27.el7.x86_64
boost-wave-1.53.0-27.el7.x86_64
boost-serialization-1.53.0-27.el7.x86_64
```

Could you do make distclean; configure ...; make; make check? 

From the error message, i isn't clear if you are really building it against the side-installed BOOST.

**Comment by dongahn** [comment] 2018-07-28 19:53
Any updates?

**Comment by marceloamaral** [comment] 2018-07-28 20:43
Nop, I am still getting the same error, even though I can see the right boost path in the Makefile

`  CXX      generators/utilities_resource_query-gen.o
In file included from /usr/include/c++/5/deque:62:0,
                 from generators/gen.cpp:26:
/usr/include/c++/5/bits/stl_construct.h: In instantiation of 'void std::_Construct(_T1*, _Args&& ...) [with _T1 = boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>; _Args = {const boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>&}]':
/usr/include/c++/5/bits/stl_uninitialized.h:75:18:   required from 'static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>*, std::vector<boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>, std::allocator<boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t> > > >; _ForwardIterator = boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>*; bool _TrivialValueTypes = false]'
/usr/include/c++/5/bits/stl_uninitialized.h:126:15:   required from '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>*, std::vector<boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>, std::allocator<boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t> > > >; _ForwardIterator = boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>*]'
/usr/include/c++/5/bits/stl_uninitialized.h:281:37:   required from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>*, std::vector<boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>, std::allocator<boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t> > > >; _ForwardIterator = boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>*; _Tp = boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>]'
/usr/include/c++/5/bits/stl_vector.h:322:31:   required from 'std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>; _Alloc = std::allocator<boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t> >]'
/usr/include/boost/graph/detail/adjacency_list.hpp:2399:16:   required from 'void std::_Construct(_T1*, _Args&& ...) [with _T1 = boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex; _Args = {boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex&}]'
/usr/include/c++/5/bits/stl_uninitialized.h:75:18:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/c++/5/bits/stl_uninitialized.h:281:37:   required from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex*; _ForwardIterator = boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex*; _Tp = boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex]'
/usr/include/c++/5/bits/stl_uninitialized.h:303:2:   required from '_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex*; _ForwardIterator = boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex*; _Allocator = std::allocator<boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex>]'
/usr/include/c++/5/bits/vector.tcc:563:7:   required from 'void std::vector<_Tp, _Alloc>::_M_default_append(std::vector<_Tp, _Alloc>::size_type) [with _Tp = boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex; _Alloc = std::allocator<boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]'
/usr/include/c++/5/bits/stl_vector.h:676:21:   required from 'void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type) [with _Tp = boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex; _Alloc = std::allocator<boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config::stored_vertex>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]'
/usr/include/boost/graph/detail/adjacency_list.hpp:2192:7:   required from 'typename Config::vertex_descriptor boost::add_vertex(boost::vec_adj_list_impl<G, C, B>&) [with Graph = boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >; Config = boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config; Base = boost::directed_graph_helper<boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char> >, boost::vecS, boost::vecS, boost::directedS, Flux::resource_model::resource_pool_t, Flux::resource_model::resource_relation_t, std::__cxx11::basic_string<char>, boost::listS>::config>; typename Config::vertex_descriptor = long unsigned int]'
generators/gen.cpp:190:44:   required from here
/usr/include/c++/5/bits/stl_construct.h:75:7: error: use of deleted function 'boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>::stored_edge_property(const boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>&)'
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^
In file included from /usr/include/boost/graph/adjacency_list.hpp:246:0,
                 from ./schema/resource_graph.hpp:29,
                 from ./generators/gen.hpp:30,
                 from generators/gen.cpp:30:
/usr/include/boost/graph/detail/adjacency_list.hpp:290:11: note: 'boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>::stored_edge_property(const boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>&)' is implicitly declared as deleted because 'boost::detail::stored_edge_property<long unsigned int, Flux::resource_model::resource_relation_t>' declares a move constructor or move assignment operator
     class stored_edge_property : public stored_edge<Vertex> {
           ^
Makefile:969: recipe for target 'generators/utilities_resource_query-gen.o' failed
make[3]: *** [generators/utilities_resource_query-gen.o] Error 1
make[3]: Leaving directory '/home/mamaral/packages/flux/flux-sched/resource'
Makefile:1038: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/mamaral/packages/flux/flux-sched/resource'
Makefile:490: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/mamaral/packages/flux/flux-sched'
Makefile:422: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by dongahn** [comment] 2018-07-28 20:57
Hm. If this continues to be a problem, comment out resource subdirectory in https://github.com/flux-framework/flux-sched/blob/master/Makefile.am#L4 and jobspec from https://github.com/flux-framework/flux-sched/blob/master/configure.ac#L59.

This will turn off the `resource` layer so some tests will fail with `make check`. But ignore them for now since this layer isn't hooked to the rest of the systems.

**Comment by SteVwonder** [comment] 2018-07-28 21:00
@marceloamaral: can you post the entire input & output of `configure` and `make` to a gist (https://gist.github.com/)?  That way we can see everything that happens before the error?  This looks like a linking issue, but it is hard to diagnose without the output from configure.

Also the spack package that I mentioned earlier is complete and posted as a PR if that interests you: https://github.com/spack/spack/pull/8818

**Comment by DavidPoliakoff** [comment] 2018-09-26 23:30
Yeah, I tried your answer (@dongahn ) to the issue and it worked just fine, thanks

**Comment by dongahn** [comment] 2018-09-26 23:32
@DavidPoliakoff: awesome! If you have autoconf patch etc, feel free to post a PR. Otherwise, either @SteVwonder and I can work on a quick PR.

**Comment by SteVwonder** [comment] 2018-09-26 23:50
@DavidPoliakoff: to help with debugging/reproducing this, what version of boost were you using?  I didn't catch a version number in the config log gist.

**Comment by SteVwonder** [comment] 2018-10-24 17:40
@marceloamaral, were you able to resolve this issue?  If not, could you post the output from your configure/make in a gist?

@DavidPoliakoff, do you happen to know the version of boost you were using?

I'm hoping to gather enough information about your environments to hopefully reproduce this with spack on my machine.

**Comment by dongahn** [comment] 2018-10-24 17:43
If we find more boost versions with bugs, we should augment:  https://github.com/flux-framework/flux-sched/blob/master/m4/ax_buggy_boost_graph.m4#L40

**Comment by dongahn** [comment] 2018-12-14 02:20
Closing. We add more configure support to detect buggy Boost versions. We may find more buggy versions in which case we will update our config script.

**Closed by dongahn** 2018-12-14 02:20 UTC
