### ISSUE TITLE
Best ways to provide consistent resrc in different reader modes

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#157] opened 2016-04-25 18:33 UTC
We agreed to move the discussion into a separate issue ticket to capture the issues in a general sense.

Below is the copy and paste of the initial discussion on a specific problem (PR #155), which has led to a problem on match tests between the RDL spec file and hwloc info. In general,  inconsistency in the semantics of `resrc`'s fields under different reader modes can lead to undesirable side effects. One specific case here was, resrc sets the name field to be the base name for the node type in rdl reader mode vs. the hostname in hwloc reader mode. 

There was also a question as to how RDL can be extended to support various hostname conventions. If we want to generate significant discussions on this subject, I will create another issue ticket. 

@grondo posted:
> One question: You mention that sched "sets name to hostname" in hwloc reader mode. RDL itself is not supposed to be node-centric and therefore in Lua-based rdl config code rdl_resource_name() does not differentiate between "node" types vs other types, and will return name+id for any resource that has an ID field. (e.g. { name: "core", id: 1 } returns rdl_resource_name() == "core1")

> I just wanted to make sure this doesn't further affect sched if it is currently behaving node-centric

@dongahn posted:
> @grondo: Thank you for the quick response and good question!

> @lipari should chime in for this question. If I read hwloc reader code correctly in here, the name of resrc is actually set to name+id where id is the logical index of hwloc_object_t type except for the node type. For node, resrc sets it to hostname -- and we had some issues when it didn't do it that way: PR #109.

> I think it will be good if we go through resrc to make sure it builds its internal fields consistently across different reader modes: rdl and hwloc. To me, it is okay as far as the name always returns the same information regardless of the reader mode. You may have a different opinion though.

@lipari posted:
> @grondo, the resrc code mirrors the conventions established with RFC 4 as well as the rdl code itself. When generating a resrc_t object from an RDL file, I opted to use the rdl_resource_json() instead of the rdl_resource_name() call. I'd have to check, but if the "name" field is getting an id appended, that is where it comes from.

**Comment by lipari** [comment] 2016-04-25 19:48
@dongahn, thank you for creating the issue and summarizing the issues.  I have a number of items that summarize my understanding of the details:

* (reiterating...) the model needs to apply to all resources, not just nodes
* The discussion starts with the terms defined in [RFC 4](https://github.com/flux-framework/rfc/blob/master/spec_4.adoc)
* the convention that the rdl code established is for the "name" field to be devoid of an "id".  Hence a node "name" could be "hype" and the "id" could be 356.
* For LC systems, the hostname could be constructed by concatenating "name" + "id".
* The "path" field is intended to reflect the composite hierarchy.  Hence, the path for a core could be "/hype/hype356/numanode1/socket1/core14"
* The last bullet implies that the "path" needs to include "id" components.  Otherwise the last example would have been "/hype/hype/numanode/socket/core14
* The hwloc library returns the "name" for the node resource as a "HostName".  For LC systems, this includes the id (e.g., hype356).
* This led to the problem that @dongahn sought to address in [PR 155](https://github.com/flux-framework/flux-sched/pull/155)

So, here's the proposal.  Let's make the rdl and resrc "name" field include the id.  The "id" field could be a optional component that is -1 when it does not apply.  Here are a few examples:

```
**core:**
name:  core47
type: core
id: 47

**node:**
name: hype356
type: node
id: 356
(note: now hwloc's HostName field matches resrc's "name")

**node:**
name:  xyz9abc
type: node
id:  -1
(again: hwloc's HostName field matches resrc's "name")
```
Bonus:  The "path" construction just becomes a straight concatenation of the "name" fields.  For example:  "/hype/hype356/numanode1/socket1/core14"

**Comment by dongahn** [comment] 2016-04-25 20:04
@lipari: I think this is reasonable from the semantics point of view. But from the implementation point of view, what @grondo is saying is this can impede condensed international representation if name+id needs to be stored *and* RDL's json method is supposed to return this internal representation.

We need @grondo's take on it.

One other question is whether we will ever see other types of readers. If so, resrc will probably need "normalized" method anyway in the end.


________________________________

**Comment by lipari** [comment] 2016-04-25 20:12
I'd like to remove the ambiguity in [RFC 4](https://github.com/flux-framework/rfc/blob/master/spec_4.adoc):

* Name or Basename

And clarify whether this particular field should be a name (core47) or basename (core).  Maybe that will render the "id" field irrelevant and unnecessary.

In any case, I don't think the fix should be made to the resrc code.  The resrc code should implement the convention we decide.

**Comment by grondo** [comment] 2016-04-25 20:54
I agree the problem is in the ambiguity in RFC 4 with "name or basename".

The id field will certainly remain necessary (you still need to know the logical/physical id of a resource), but how about the following improvement by differentiating "name" and "basename"

 * Basename: a base name (prefix) of a resource. By default the resource type name.
 * ID: a logical numeric identifier differentiating resources of the same basename (optional)
 * Name: By default, the resource basename with the ID appended, if ID is set.

The RDL config reader we have now would then be enhanced to return the basename and name explicitly in the json representation of the object.

Alternately, I also liked @trws idea of allowing a resource attribute that allows "name" to be a substitution of the basename and id, or any other arbitrary resource attribute. The default would be `"${basename}${id}"`, but this allows a lot more flexibility like `"${basename}-${id}"` or `"${basename}${id?"-"}${id}"` (using some invented substitution that substitues "-" if `id` is set.)

**Comment by lipari** [comment] 2016-04-25 21:14
@grondo, that sounds good to me.  For the record, we may need to provide for multiple id's in the "name" attribute of a node for node.  For example, some sites like to name their nodes R12M2 to refer to the 2nd frame in the 12th rack.

I also think we ought to allow id's to be N/A.  This would be the case for the "cluster" resource for example where giving it an "id" if 0 could be misleading.  I suggest id == -1 to designate N/A.

**Comment by grondo** [comment] 2016-04-25 21:26
@lipari, "id" is already optional. If not set it is `nil` `NULL` "N/A" or whatever you want to call it.

Your first point argues for @trws's suggestion. For node resource objects at the site in your example, site-specific attributes "bladeid" and "rackid" could be set on the resource, and the name would be defined as `"R${rackid}B${bladeid}"`.

**Comment by lipari** [comment] 2016-04-25 21:32
@grondo and @dongahn, I'd be happy to submit a PR that implements the changes we've decided.  It will affect the rdl and resrc code and any tests that may be affected.

**Comment by grondo** [comment] 2016-04-25 21:35
@lipari, sounds great! Should we also set up a PR for RFC #4? We could enhance the RFC with changes above, plus an extension to register a per resource template to create resource name from instance parameters, but for now that functionality could be marked as "not yet implemented"

**Comment by lipari** [comment] 2016-04-25 21:37
Will do.

**Comment by dongahn** [comment] 2016-04-25 21:44
@lipari: this sounds good to me. I will wait until your PR is merged before adapting PR #155 to it. 

@grondo: Putting the proposed change as a PR for RFC #4 with NYI placeholder makes sense to me unless someone wants to put more thoughts to it and pin down the spec/mechanism. At the very least, this PR should refer to this issue ticket for a future reference.

**Comment by trws** [comment] 2016-04-26 04:30
This all sounds good to me.  The only question that comes to mind after going over this in post, should we have a "hostname" default field that would represent the actual resolvable hostname, as possibly distinct from the "name" field? I'm not sure if we need it, but given the defaults it seems like "Node15" would be consistent naming, where the hostname might be entirely something else.  Perhaps I'm overthinking it...

**Comment by grondo** [comment] 2016-04-26 04:55
Though I don't see it mentioned in rfc4, resources in the Flux model are allowed to have arbitrary attributes. A DNS hostname could be an arbitrary attribute that would be applied to specific resources of type "node". It probably doesn't make sense to require all resources to have a hostname.

Specific schedulers or other users of the resource model could specify in documentation and/or during verification that the resolvable name of a "node" or host type resource is assumed to be the "name" of the resource as described above, or overridden by a "hostname" attribute if set.

Similar schemes could be used for other resource types that might have similar requirements, e.g. management names for switches, pdus, and so on.

**Comment by lipari** [comment] 2016-05-05 15:09
[PR 41](https://github.com/flux-framework/rfc/pull/41) to rfc has been merged.
[PR 161](https://github.com/flux-framework/flux-sched/pull/161) to flux-sched is ready for review.

**Closed** 2016-05-10 06:17 UTC
