### ISSUE TITLE
job lost due to qmanager restart

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#608] opened 2020-02-29 06:18 UTC
A CI job failed during a test of #605.  The relevant test is [t1002-qmanager-reload.t](https://github.com/flux-framework/flux-sched/blob/master/t/t1002-qmanager-reload.t).  The relevant logs are:

test-script output
```
expecting success: 

    flux module remove qmanager &&
    flux module load qmanager &&
    flux job list > jobs.list2 &&
    diff jobs.list2 jobs.list

2d1
< {"id": 11442061312, "userid": 2000, "priority": 16, "t_submit": 1582953004.6481304, "state": 4, "name": "hostname", "ntasks": 1, "t_depend": 1582953004.6481304, "t_sched": 1582953004.6600838}
not ok 5 - qmanager: restart keeps the main job queue intact
```

dmesg
```
2020-02-29T05:10:04.619644Z qmanager.debug[0]: alloc success (id=10720641024)
2020-02-29T05:10:04.639460Z job-manager.debug[0]: submit_cb: added 1 jobs
2020-02-29T05:10:04.660067Z job-manager.debug[0]: submit_cb: added 1 jobs
2020-02-29T05:10:04.679174Z broker.debug[0]: rmmod qmanager
2020-02-29T05:10:04.679250Z job-manager.debug[0]: alloc: stop due to alloc response error: Function not implemented
2020-02-29T05:10:04.679278Z qmanager.debug[0]: service_unregister
2020-02-29T05:10:04.679342Z broker.debug[0]: module qmanager exited
2020-02-29T05:10:04.690664Z broker.debug[0]: insmod qmanager
2020-02-29T05:10:04.691011Z qmanager.debug[0]: service_register
2020-02-29T05:10:04.691084Z job-manager.debug[0]: scheduler: hello
2020-02-29T05:10:04.693787Z job-manager.debug[0]: scheduler: ready single
```

---
*Below lies the late-night conjectures of an individual wholly unfamiliar with the relevant protocols and designs.  Reader beware.*

I'm guessing the problem is that while an alloc RPC from job-manager to qmanager was in flight, the qmanager was restarted, leading to an alloc response error.  I suspect that the job-manager could be improved to more gracefully handle this case (@garlick any thoughts?).   Another suspicion is that putting a `flux queue disable` call before the module restart and a `flux queue enable` afterwards would make the test not racy (without addressing the underlying race).  If not, maybe we need a command to pause the back-and-forth between job-manager and the scheduler to enable graceful, controlled restarts of the scheduler.

**Comment by dongahn** [comment] 2020-02-29 06:44
I think your late night conjecture is correct :-). To me, "alloc: stop due to alloc response error" seems pretty graceful for now given we don't have full resiliency. By the time, our project gets to communication resiliency using things like "retries", I can see at the network level the request gets retried with some backoff protocols and such and maybe this class of errors (transient service up/down) etc can be handle "generally" more graceful. @garlick may think differently though.

**Comment by garlick** [comment] 2020-02-29 15:54
> I'm guessing the problem is that while an alloc RPC from job-manager to qmanager was in flight, the qmanager was restarted, leading to an alloc response error. I suspect that the job-manager could be improved to more gracefully handle this case

That actually is the design.  The job manager treats an error response to an alloc request as a signal that the scheduler has gone away.   It then considers all outstanding alloc requests to be no longer pending, and puts those jobs back in its internal queue.  When the scheduler reloads and goes through the hello + ready handshake, those alloc requests should be resent.   The logs don't show anything unexpected that I can see.

I'll have a closer look at the test - I'm wondering if there is any other way a job could be "missing"?

**Comment by garlick** [comment] 2020-02-29 16:15
Those jobs have a "simulated" exec time of 1s.  Is it possible that in the slow travis environment one of them completed unexpectedly?

**Comment by dongahn** [comment] 2020-02-29 16:45
I think it is possible. Even if it is not practically, there is a synchronization violation. Maybe we should use flux jobs tool and list both running and successfully completed jobs to match the job count.

Or if we are willing to make this test run a little longer, we can wait for all the submitted jobs to complete and check if the count matches.

**Comment by garlick** [comment] 2020-02-29 16:52
Any running jobs are canceled in rc3 now, so it seems like you could just increase the runtime of each job to an arbitrarily large value, and it would effectively close the race without increasing the length of time to run the test?

**Comment by dongahn** [comment] 2020-02-29 18:06
Well, I should have looked at the test code more closely. Yes, it looks to me like increasing the runtime to a large value should fix the issue.

**Comment by chu11** [comment] 2020-03-07 02:02
Just wanted to check if this is a duplicate of #585 ?

**Comment by dongahn** [comment] 2020-03-07 02:06
@chu11: could be. We just need to test this more.

**Comment by dongahn** [comment] 2020-03-07 07:36
I am no longer sure if this problem is due to the completion of 1-sec jobs before the reload. I added 20 secs before unloading `qmanager` and this test still succeeds in my environment to my surprise. 

```diff
 test_expect_success 'qmanager: hwloc reload works' '
@@ -49,16 +49,21 @@ test_expect_success 'qmanager: submit 2 more as many jobs as there are cores ' '
     jobid3=$(flux job submit basic.json) &&
     flux job wait-event -t 2 ${jobid3} submit &&
     flux job list > jobs.list &&
+    flux jobs > jobs99.list &&
     echo ${jobid1} > jobid1.out &&
     echo ${jobid2} > jobid2.out &&
-    echo ${jobid3} > jobid3.out
+    echo ${jobid3} > jobid3.out &&
+    false
 '

 test_expect_success 'qmanager: restart keeps the main job queue intact' '
+    sleep 20 &&
     flux module remove qmanager &&
     flux module load qmanager &&
     flux job list > jobs.list2 &&
-    diff jobs.list2 jobs.list
+    flux jobs > jobs999.list &&
+    diff jobs.list2 jobs.list &&
+    false
 '
```

```
             JOBID USER     NAME       STATE    NTASKS NNODES  RUNTIME RANKS
       21474836480 ahn1     hostname   SCHED         1      -        - -
       22045261824 ahn1     hostname   SCHED         1      -        - -
       20904411136 ahn1     hostname   RUN           1      1   0.195s 0
       20367540224 ahn1     hostname   RUN           1      1   0.226s 0
       19763560448 ahn1     hostname   RUN           1      1   0.261s 0
       19176357888 ahn1     hostname   RUN           1      1   0.296s 0
       18505269248 ahn1     hostname   RUN           1      1   0.336s 0
       17968398336 ahn1     hostname   RUN           1      1   0.369s 0
       17465081856 ahn1     hostname   RUN           1      1   0.401s 0
       16944988160 ahn1     hostname   RUN           1      1   0.431s 0
       16374562816 ahn1     hostname   RUN           1      1   0.462s 0
       15737028608 ahn1     hostname   RUN           1      1   0.502s 0
       15200157696 ahn1     hostname   RUN           1      1   0.534s 0
       14696841216 ahn1     hostname   RUN           1      1   0.566s 0
       14092861440 ahn1     hostname   RUN           1      1   0.600s 0
       13589544960 ahn1     hostname   RUN           1      1   0.632s 0
       13019119616 ahn1     hostname   RUN           1      1   0.665s 0
       12398362624 ahn1     hostname   RUN           1      1   0.699s 0
ahn1@5143115d7118:/usr/src/t$ cat trash-directory.t1002-qmanager-reload/jobs999.list
             JOBID USER     NAME       STATE    NTASKS NNODES  RUNTIME RANKS
       21474836480 ahn1     hostname   SCHED         1      -        - -
       22045261824 ahn1     hostname   SCHED         1      -        - -
       20904411136 ahn1     hostname   RUN           1      1   20.42s 0
       20367540224 ahn1     hostname   RUN           1      1   20.45s 0
       19763560448 ahn1     hostname   RUN           1      1   20.48s 0
       19176357888 ahn1     hostname   RUN           1      1   20.52s 0
       18505269248 ahn1     hostname   RUN           1      1   20.56s 0
       17968398336 ahn1     hostname   RUN           1      1   20.59s 0
       17465081856 ahn1     hostname   RUN           1      1   20.62s 0
       16944988160 ahn1     hostname   RUN           1      1   20.65s 0
       16374562816 ahn1     hostname   RUN           1      1   20.68s 0
       15737028608 ahn1     hostname   RUN           1      1   20.72s 0
       15200157696 ahn1     hostname   RUN           1      1   20.75s 0
       14696841216 ahn1     hostname   RUN           1      1   20.79s 0
       14092861440 ahn1     hostname   RUN           1      1   20.82s 0
       13589544960 ahn1     hostname   RUN           1      1   20.85s 0
       13019119616 ahn1     hostname   RUN           1      1   20.89s 0
       12398362624 ahn1     hostname   RUN           1      1   20.92s 0
```

My guess is the wall time isn't enforced for emulated test jobs as well... (Can't find that issue ticket)... If that's the case, why the test intermittently failing is still mysterious. 

I will still post a change that increases the wall time though.

**Comment by dongahn** [comment] 2020-03-19 04:50
https://github.com/flux-framework/flux-sched/pull/617 is supposed to fix this issue. If the problem still manifests itself, we can reopen.

**Closed by dongahn** 2020-03-19 04:50 UTC
